---
- name: Create repository for Elasticsearch
  copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: Install Elasticsearch latest 5.x
  yum:
    name: elasticsearch
    state: present
    allow_downgrade: yes
  notify: "restart elasticsearch"

- name: Copy default configuration for Elasticsearch
  copy:
    src: etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    dest: /etc/elasticsearch/
  notify: "restart elasticsearch"

- name: Copy JVM options for Elasticsearch
  copy:
    src: etc/elasticsearch/jvm.options
    owner: elasticsearch
    group: elasticsearch
    dest: /etc/elasticsearch/
  notify: "restart elasticsearch"

- name: Update /etc/security/limits.conf for nofile
  pam_limits:
    domain: elasticsearch
    limit_type: '-'
    limit_item: nofile
    value: '65536'
  notify: "restart elasticsearch"

- name: Update /etc/security/limits.conf for nproc
  pam_limits:
    domain: elasticsearch
    limit_type: '-'
    limit_item: nproc
    value: '4096'
  notify: "restart elasticsearch"

- name: Update sysctl.conf for Elasticsearch
  sysctl:
    name: vm.swappiness
    value: '1'
    state: present
    reload: yes
  notify: "restart elasticsearch"
  when: not ci|bool

- name: start elasticsearch service
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
  when: not ci|bool
