---
- name: restart postgresql service on Centos
  ansible.builtin.service:
    name: postgresql-11
    state: restarted
  listen: "restart postgresql"
  when:
    - ansible_distribution == 'CentOS'

- name: restart postgresql service on Ubuntu
  ansible.builtin.service:
    name: postgresql
    state: restarted
  listen: "restart postgresql"
  when:
    - ansible_distribution == 'Ubuntu'
