---
galaxy_info:
  role_name: minio
  author: Sido Haakma
  description: Minio file storage, used to get data into the federated platform
  company: MOLGENIS
  license: LGPL
  min_ansible_version: 1.2
  platforms:
    - name: CentOS
      versions:
        - 8
        - 7
    - name: RHEL
      versions:
        - 8
        - 7
    - name: Ubuntu
      versions:
        - 20
  galaxy_tags: [molgenis]
dependencies: []
