---
- name: NginX based on OS
  include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: Start and enable nginx (at boot time)
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started

- name: Add in memory robots.txt to nginx
  ansible.builtin.copy:
    src: robots.conf
    dest: /etc/nginx/default.d/robots.conf
    mode: '0644'
  notify: "restart nginx"

- name: Ammend /etc/hosts to include hostname
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
    state: present

- name: Install molgenis frontend config
  ansible.builtin.template:
    src: molgenis.j2
    dest: /etc/nginx/default.d/molgenis.conf
    mode: '0644'
  when: not ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '22' )
  notify: "restart nginx"

- name: Install special molgenis frontend config for OpenSSL 3.x servers
  ansible.builtin.template:
    src: molgenis_openssl3.j2
    dest: /etc/nginx/default.d/molgenis.conf
    mode: '0644'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '22'
  notify: "restart nginx"

- name: Register project from molgenis-server.properties
  ansible.builtin.shell:
    cmd: grep project /usr/local/share/molgenis/molgenis-server.properties | cut -d'=' -f2
  changed_when: false
  register: project_name

- name: Ammend nginx frontends for track and trace
  ansible.builtin.lineinfile:
    dest: /etc/nginx/default.d/molgenis.conf
    insertafter: '# extra special frontends below'
    line: "    rewrite ^/@molgenis-ui/track-and-trace/(.+) /@molgenis-ui/track-and-trace@1.1.4/$1;"
    state: present
  when: project_name.stdout == 'trace'
