---
- name: Install NginX
  apt:
    state: present
    name: nginx

- name: Create folder structure
  file:
    state: directory
    owner: root
    group: root
    mode: '0755'
    path: "/etc/nginx/default.d"

- name: Customize nginx.conf
  copy:
    src: nginx.conf_debian
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: "restart nginx"
