---
galaxy_info:
  role_name: tomcat
  author: Erik Schaberg
  description: this role is part of the Molgenis installation
  company: UMCG/RUG
  license: license (GPLv3)
  min_ansible_version: 2.7.9
  platforms:
    - name: CentOS
      versions:
        - 8
        - 7
    - name: RHEL
      versions:
        - 8
        - 7
    - name: Rocky
      versions:
        - 8
    - name: Ubuntu
      versions:
        - 20
  galaxy_tags: [molgenis]
dependencies: []
