---
- name: remove unnecessary dependencies | Cleanup (Debian)
  ansible.builtin.apt:
    state: absent
    name: "{{ item }}"
  with_items:
    - openjdk-{{ dependencies.java.version }}-jre-headless

- name: prune all dangling container resources | Cleanup (Debian)
  ansible.builtin.command: docker system prune -a -f
