---
- name: dnf | Installation (RedHat)
  yum:
    state: present
    name:
      - dnf
    update_cache: yes
    
- name: enable subscription | Configuration (RedHat)
  community.general.redhat_subscription:
    state: present
    username: "{{ redhat.subscription.username }}"
    password: "{{ redhat.subscription.password }}"
    auto_attach: true
  when: redhat.subscription.enabled == true 

- name: java | Installation (RedHat)
  dnf:
    state: present
    name: java-{{ version }}-openjdk-headless
    update_cache: yes
