---
- name: dnf | Installation (Rocky)
  yum:
    state: present
    name:
      - dnf
    update_cache: yes

- name: java | Installation (Rocky)
  dnf:
    state: present
    name: java-{{ version }}-openjdk-headless
    update_cache: yes
