---
- name: NginX based on OS
  include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: Start and enable nginx (at boot time)
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Add in memory robots.txt to nginx
  copy:
    src: robots.conf
    dest: /etc/nginx/default.d/robots.conf
    mode: '0644'
  notify: "restart nginx"

- name: Ammend /etc/hosts to include hostname
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
    state: present

- name: Install molgenis frontend config
  template:
    src: molgenis.j2
    dest: /etc/nginx/default.d/molgenis.conf
    mode: '0644'
  notify: "restart nginx"

- name: Register project from molgenis-server.properties
  shell:
    cmd: grep project /usr/local/share/molgenis/molgenis-server.properties | cut -d'=' -f2
  changed_when: false
  register: project_name

- name: Ammend nginx frontends for track and trace
  lineinfile:
    dest: /etc/nginx/default.d/molgenis.conf
    insertafter: '# extra special frontends below'
    line: "    rewrite ^/@molgenis-ui/track-and-trace/(.+) /@molgenis-ui/track-and-trace@1.1.4/$1;"
    state: present
  when: project_name.stdout == 'trace'
