---
- name: allow changing release-info apt-repositories | Configuration
  ansible.builtin.command: apt update -y --allow-releaseinfo-change
  tags:
    - skip_ansible_lint

- name: add keyring | Repository configuration (Debian)
  ansible.builtin.apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add docker | Repository configuration (Debian)
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present
