---
- name: stop firewall | Pre-installation
  systemd:
    name: firewalld
    state: stopped

- name: acme - directories | Configuration
  file:
    path: "{{ item }}"  
    state: directory
  loop:
    - /usr/local/share/acme
    - /etc/ssl/certs/{{ domains.armadillo }}
    - /etc/ssl/certs/{{ domains.auth }}
    - /etc/ssl/certs/{{ domains.storage }}

- name: acme - get | Installation
  get_url:
    url: https://get.acme.sh
    dest: /usr/local/share/acme/acme.sh
    mode: 0755

- name: acme - unpack | Installation
  command: /usr/local/share/acme/acme.sh

- name: acme - register account | Configuration
  command: /root/.acme.sh/acme.sh --register-account -m {{ letsencrypt.acme.email }}

- name: acme - domain generation | Configuration
  command: /root/.acme.sh/acme.sh --issue --standalone -d {{ item }} --force
  with_items:
    - '{{ domains.armadillo }}'
    - '{{ domains.auth }}'
    - '{{ domains.storage }}'

- name: acme - certificate installation | Installation
  file:
    src: /root/.acme.sh/{{ item }}/fullchain.cer
    dest: /etc/ssl/certs/{{ item }}/{{ item }}.cer
    state: link
  with_items: 
    - '{{ domains.armadillo }}'
    - '{{ domains.auth }}'
    - '{{ domains.storage }}'

- name: acme - private key installation | Installation
  file:
    src: /root/.acme.sh/{{ item }}/{{ item }}.key
    dest: /etc/ssl/certs/{{ item }}/{{ item }}.key
    state: link
  with_items: 
    - '{{ domains.armadillo }}'
    - '{{ domains.auth }}'
    - '{{ domains.storage }}'

- name: acme - install autoamtic renewal | Configuration
  copy:
    src: ssl_renewal.bash
    dest: /usr/local/bin/ssl_renewal.bash
    mode: '0755'

- name: acme - install automatic renewal | Installation
  cron: 
   minute="20" 
   hour="5" 
   weekday="*"
   name="Automatic SSL-certificate renewal"
   user="root"
   cron_file="ssl_renewal"
   job="/usr/local/bin/ssl_renewal"

- name: start firewall | Post-installation
  systemd:
    name: firewalld
    state: started
