---
- name: remove unnecessary dependencies | Cleanup (RedHat)
  dnf:
    state: absent
    name: "{{ item }}"
  with_items:
    - java-{{ dependencies.java.version }}-openjdk-headless

- name: prune all dangling container resources | Cleanup (RedHat)
  command: podman system prune -a -f
