---
- name: Install HTTPD and HTTPD-modules
  dnf:
    state: present
    name:
      - httpd
      - mod_ssl
      - python3-libsemanage
  when: httpd.setup|bool

- name: Register if first install HTTPD
  stat:
    path: /etc/httpd/conf.d/welcome.conf
  register: httpd_first_install
  when: httpd.setup|bool

- name: Delete default files in HTTPD conf.d directory
  file:
    state: absent
    path: "/etc/httpd/conf.d/{{ item }}"
  with_items:
    - autoindex.conf
    - README
    - userdir.conf
    - welcome.conf
    - ssl.conf
  when: httpd_first_install.stat.exists and httpd.setup|bool

- name: Start and enable HTTPD (at boot time)
  systemd:
    name: httpd
    enabled: yes
    state: started
  when: httpd.setup|bool

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: not ci|bool and httpd.setup|bool

- name: Create additional configuration directories for HTTPD
  file:
    path: /etc/httpd/conf.modules.d/
    state: directory
  when: httpd.setup|bool

- name: Add robots.txt file
  copy:
    src: robots.txt
    dest: /var/www/robots.txt
  when: not ci|bool and httpd.setup|bool

- name: Insert/Update robots.txt configuration stanza in /etc/httpd/conf/httpd.conf
  blockinfile:
    path: /etc/httpd/conf/httpd.conf
    block: |
      # global robots.txt file stopping the crawlers (good ones anyway)
      <Location "/robots.txt">
          ProxyPass !
      </Location>
      Alias /robots.txt /var/www/robots.txt
  notify: "restart web services"

- name: Set ServerName in default config to localhost
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: ServerName localhost:80
    state: present

- name: Add additional configuration files
  copy:
    src: "{{ item }}"
    dest: /etc/httpd/conf.modules.d/
  with_items:
    - 99-molgenis.conf
    - 98-compression.conf
  when: httpd.setup|bool
  notify: "restart web services"

- name: Set conf.modules.d as configuration directory in httpd.conf
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: Include conf.modules.d/*.conf
    state: present
  when: httpd.setup|bool
  notify: "restart web services"

#- name: Ammend /etc/hosts to include hostname
#  lineinfile:
#    dest: /etc/hosts
#    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
#    state: present
#  when: httpd.setup|bool

- name: Create certificate-directories for SSL
  file:
    path: /etc/pki/tls/certs/{{ inventory_hostname }}/
    state: directory
  when: httpd.setup|bool and httpd.ssl|bool

#    - name: Install SSL certs
#      copy:
#        content: "{{ lookup('hashi_vault',
#        'secret=secret/ops/certificate/ssl/wildcard/gcc.rug.nl:{{ item }}
#        token={{ vault.token }} url=http://localhost:8200') }}"
#        dest: "/etc/pki/tls/certs/{{ inventory_hostname }}/{{ item }}"
#      with_items:
#        - certificate.crt
#        - private.key
#        - serverchain.crt
#      when: not ci|bool and httpd.setup|bool and httpd.ssl|bool

- name: Copy SSL config file
  template:
    src: options-ssl-httpd.j2
    dest: /etc/httpd/conf.d/options-ssl-httpd.conf
  when: not ci|bool and httpd.setup|bool
  notify: "restart web services"

#    - name: Stop connection to Vault
#      command: pkill kubectl -9
#      delegate_to: localhost
#      changed_when: false
#      run_once: true
#      when: not ci|bool and httpd.setup|bool and httpd.ssl|bool

- include_role:
    name: httpd_virtualhost
