# required
namespace: molgenis
name: armadillo
version: 1.3.6
readme: README.md
authors:
- Sido Haakma <s.haakma@rug.nl>

# optional
description: Armadillo is a service which can be used to perform federated analysis
license:
- LGPL-2.0-or-later
tags: [federation]
#dependencies: {}
repository: https://github.com/molgenis/molgenis-service-armadillo
documentation: https://github.com/molgenis/molgenis-service-armadillo
homepage: https://molgenis.org
issues: https://github.com/molgenis/molgenis-service-armadillo/issues
dependencies: 
  "community.docker": ">=1.7.0"
  "containers.podman": ">=1.5.0"

