---
- hosts: all # needs to be: 'localhost' if local connection is set
  become: true
  # connection: local 
  become_user: root
  gather_facts: true

  roles:
    - role: migrate
      vars:
        users:
          # - { source_user: sido, target_user: user-298371298312 }
          # - { source_user: tim, target_user: user-987348932734 }