---
- name: Create molgenis group
  group:
    name: molgenis

- name: Create tomcat uid
  user:
    name: tomcat
    group: molgenis
    shell: /bin/false

- name: Register if tomcat is already there
  stat:
    path: /usr/share/apache-tomcat-9.0.39/
  register: tomcat_already_there

- name: Install Tomcat from source for centos8
  unarchive:
    src: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.39/bin/apache-tomcat-9.0.39.tar.gz"
    dest: "/usr/share/"
    owner: tomcat
    group: molgenis
    copy: no
  when: not tomcat_already_there.stat.exists

- name: Register if first install tomcat
  stat:
    path: /usr/share/apache-tomcat-9.0.39/webapps/examples
  register: tomcat_first_install

- name: Delete default folders tomcat webapps directory
  file:
    state: absent
    path: "/usr/share/apache-tomcat-9.0.39/webapps/{{ item }}"
  with_items:
    - ROOT
    - docs
    - examples
    - host-manager
    - manager
  when: tomcat_first_install.stat.exists

- name: create softlink to tomcat logs
  file:
    src:  /usr/share/apache-tomcat-9.0.39/logs
    dest: /var/log/tomcat
    state: link

- name: create softlink to tomcat conf
  file:
    src:  /usr/share/apache-tomcat-9.0.39/conf
    dest: /etc/tomcat
    state: link

- name: create softlink to tomcat shortname
  file:
    src:  /usr/share/apache-tomcat-9.0.39
    dest: /usr/share/tomcat
    state: link

- name: Install molgenis server.xml file for tomcat
  copy:
    src: server.xml
    dest: /usr/share/apache-tomcat-9.0.39/conf/server.xml

- name: Install systemctl services file for tomcat
  template:
    src: tomcat.j2
    dest: /etc/systemd/system/tomcat.service

- name: Start and enable Tomcat (at boot time)
  systemd:
    name: tomcat
    enabled: yes
    masked: no
    daemon_reload: yes
  notify: "start tomcat"
