---
galaxy_info:
  role_name: deps_compose
  author: Sido Haakma
  description: Installs docker-compose or podman-compose on the operating system
  company: MOLGENIS

  license: LGPL

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "8"
        - "7"
    - name: Ubuntu
      versions:
        - focal
    - name: Debian
      versions:
        - buster

  galaxy_tags: [federation]
