---
- name: minio service file exists | Checks
  stat:
    path: /etc/systemd/system/minio.service
  register: minio_service

- name: install service file | Configuration
  get_url:
    url: https://raw.githubusercontent.com/minio/minio-service/master/linux-systemd/minio.service
    dest: /etc/systemd/system/minio.service
    mode: '0644'
  when: not minio_service.stat.exists

- name: replace minio-user | Configuration
  replace:
    path: /etc/systemd/system/minio.service
    regexp: 'minio-user'
    replace: 'minio'
  when: not minio_service.stat.exists

- name: add minio group | Configuration
  group:
    name: minio

- name: add minio user | Configuration
  user:
    name: minio
    group: minio

- name: create directories | Configuration
  file:
    path: "{{ item }}"
    owner: minio
    group: minio
    state: directory
    mode: '0755'
  with_items:
    - /var/lib/minio
    - /var/lib/minio/data

- name: minio | Configuration
  get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.{{ version }}
    dest: /usr/local/bin/minio
    mode: '0755'
    owner: minio
    group: minio

- name: minio | Configuration
  template:
    src: minio.j2
    dest: /etc/default/minio
    owner: minio
    group: minio
    mode: '0755'
  notify:
    - "restart Minio service"

- name: start and enable minio | Installation
  systemd:
    name: minio
    enabled: yes
    state: started
