---
- name: Create repository for Elasticsearch7 on RedHat
  ansible.builtin.copy:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    mode: '0644'

- name: Install Elasticsearch latest 7.x
  ansible.builtin.yum:
    name: elasticsearch
    state: present
    allow_downgrade: yes
    enablerepo: elasticsearch-7
  notify: "restart elasticsearch"
