---
- name: Deployment for MOLGENIS - operational development
  hosts: "{{ host_group }}"
  gather_facts: true
  become: true
  vars:
    host_group: "all"
    experimental: false
    ci: false
    httpd:
      setup: true
      ssl: false
      hostname: molgenis.local
    molgenis:
      setup: true
      version: 8.5.1
      ssh: true
      
  roles:
    # system configuration
    -  { role: swap_centos8, when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8' }
    -  { role: preinstall_centos8, when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8' }
    # application configuration
    -  { role: java_centos8, when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8' }
    -  { role: elasticsearch_centos8, when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8' }
    -  { role: postgres_11_centos8, when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8' }
    -  { role: minio_centos8, when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8' }
    -  { role: tomcat_centos8, when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8' }
    -  { role: molgenis_centos8, when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8' }
    -  { role: httpd_centos8, when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8' }
    # additional configuration
    -  { role: python_centos8, when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8' }
    - postinstall
