---
galaxy_info:
  role_name: tools_upgrade
  author: Sido Haakma
  description: The upgrade roles installs a script which pull the latests production images from repository every night.
  company: MOLGENIS

  license: LGPL

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "8"
        - "7"
    - name: Ubuntu
      versions:
        - focal
    - name: Debian
      versions:
        - buster

  galaxy_tags: [federation]
