---
galaxy_info:
  role_name: auth
  author: Sido Haakma
  description: Armadillo authentication implementation used allow people to use the Armadillo suite
  company: MOLGENIS

  license: LGPL

  min_ansible_version: 1.2

  github_branch: master

  platforms:
    - name: Debian
      versions:
        - 10
    - name: Ubuntu
      versions:
        - 20
    - name: CentOS
      versions:
        - 8
        - 7
    - name: RedHat
      versions:
        - 8
        - 7

  galaxy_tags: [federation]

allow_duplicates: true
