---
- name: configure cronjob | Configuration
  ansible.builtin.include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: install cronjob for automatic upgrades | Configuration
  ansible.builtin.cron:
    name: "Upgrade Armadillo stack"
    minute: "1"
    hour: "0"
    weekday: "0"
    job: "/usr/share/armadillo/upgrade-armadillo.bash"
