---
galaxy_info:
  role_name: tools_migrate
  author: Sido Haakma
  description: Migrates the Opal workspaces to the armadillo directories
  company: MOLGENIS

  license: LGPL

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "8"
        - "7"
    - name: Ubuntu
      versions:
        - focal
    - name: Debian
      versions:
        - buster

  galaxy_tags: [federation]
