---
galaxy_info:
  role_name: tools_cleanup
  author: Sido Haakma
  description: Cleans up the version 1 environment so the version 2 environment does not interfere with the version 1 environment
  company: MOLGENIS

  license: LGPL

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "8"
        - "7"
    - name: Ubuntu
      versions:
        - focal
    - name: Debian
      versions:
        - buster

  galaxy_tags: [federation]
