---
- name: enable subscription | Configuration (RedHat)
  community.general.redhat_subscription:
    state: present
    username: "{{ redhat.subscription.username }}"
    password: "{{ redhat.subscription.password }}"
    auto_attach: true
  when: redhat.subscription.enabled == true
